### PR TITLE
Finalizing comm of practice page

### PR DESCRIPTION
**Pull request by csseu**
Major changes
- Cards are a _communities collection
- Additional content
- Tweaked css
- Including for the uncanny tablet valley

Looks good to me on FF, Chrome, and Edge.

If you're not seeing any card content: In my experience with Jekyll/Docker, occasionally it won't load changes from collections and _config.yml, even when I start with a fresh server. My workaround was to dump _site in the trash and have jekyll serve everything new. (I'm wondering if that was the issue with the Liquid tag for img dir as well).

### CODE REVIEW

**Review by jbubar — CHANGES_REQUESTED** [review]
Nice Work!
Before I do a more in depth review, could you remove the files that you did not edit from the pr?
This is a common thing that I run into, but it looks like there are some files in your pr that you got from merging recent changes to fix merge conflicts or something..

check out [this article](https://ffeathers.wordpress.com/2020/03/21/removing-an-updated-file-from-a-pr-on-github/#:~:text=If%20the%20unwanted%20updates%20are,the%20file%20from%20the%20PR.). It has some commands you can use

it will look something like this.
```
#while on feature-branch
git fetch upstream gh-pages
git checkout upstream/gh-pages -- <file-name-to-revert-including-path>
git commit -m "Reverted content of file."
```
Let me know if this works or is helpful.

**Comment by jbubar** [comment]
Oh. I get it.. my bad. This is being committed into davids branch

**Comment by jbubar** [comment]
David has to merge it

**Comment by jbubar** [comment]
So sorry about my misinformed review...

Here are my thoughts...
https://github.com/hackforla/website/pull/1137#issuecomment-801320557

**Comment by csseu** [comment]
No worries! I'm dog-chemlab-meme.jpg, so this doesn't even register to me
as misinformed.

Tonight after work I'll delete this PR, make a new one directly to the H4LA
repo, and I'll try to delete those unrelated changes.

Thanks!

**Pull request closed without merging**
